// Localization data and helper functions
// Moved from callback.js

// --- UI STRINGS for popup + content script ---
const UI_STRINGS = {
  en: {
    // Popup - Header
    subtitle: "Smart Vinted listings with AI",
    // Popup - Auth
    welcomeBack: "Welcome Back",
    signInTo: "Sign in to AutoLister AI",
    continueWithGoogle: "Continue with Google",
    or: "OR",
    emailAddress: "Email Address",
    sendMagicLink: "Send Magic Link",
    needHelp: "Need help?",
    contactSupport: "Contact Support",
    // Popup - Plan
    freePlan: "Free",
    starterPlan: "Starter Plan",
    proPlan: "Pro Plan",
    businessPlan: "Business Plan",
    dailyUsage: "Daily Usage",
    monthlyUsage: "Monthly Usage",
    totalUsage: "Total Usage",
    starter: "Starter",
    pro: "Pro",
    perMonth: "/mo",
    listingsPerDay: "listings/day",
    toneEmojiFeature: "Tone & emoji customization",
    popular: "Popular",
    getStarter: "Get Starter",
    getPro: "Get Pro",
    compareAllPlans: "Compare All Plans",
    activeUntil: "Active until",
    activeSubscription: "Active subscription",
    manageSubscription: "Manage Subscription",
    contentLanguage: "Generated content language",
    selectLanguage: "Select Language",
    signOut: "Sign Out",
    helperText: 'The "Generate" button appears on Vinted item listing pages.',
    // Popup - Settings
    settings: "Settings",
    displayLanguage: "Display language",
    textFormat: "Text format",
    descriptionTone: "Description Tone",
    toneStandard: "Standard",
    toneFriendly: "Friendly",
    tonePro: "Pro",
    toneEnthusiastic: "Enthusiastic",
    useEmojis: "Use Emojis",
    emojiSublabel: "Add relevant emojis to text",
    upgradeToUnlock: "Upgrade to unlock:",
    upgradeNote:
      "Description tone options and emoji enhancement are available on Pro & Business plans.",
    viewPlans: "View Plans →",
    loading: "Loading...",
    processing: "Processing…",
    newBadge: "NEW",
    // Popup - Errors
    pleaseEnterValidEmail: "Please enter a valid email address.",
    checkEmailForLink: "Check your email for the sign-in link.",
    pleaseSignInToUpgrade: "Please sign in to upgrade.",
    unableToOpenPayment: "Unable to open the payment page.",
    connectionIssue: "Connection issue. Please try again.",
    pleaseSignInToManage: "Please sign in to manage your subscription.",
    unableToOpenSubscription: "Unable to open the subscription page.",
    googleSignInFailed: "Google sign-in failed. Please try again in a moment.",
    popupBlocked:
      "We tried to open a Google sign-in window, but it may have been blocked by your browser. Please allow pop-ups for this extension and try again.",
    // Content script
    generate: "Generate",
    phone: "Phone",
    signInToEnable: "Sign in to enable AI Tools",
    clickHere: "(Click here)",
    generating: "⏳ Generating…",
    done: "✅ Done",
    uploadFromPhone: "📱 Upload from Phone",
    featurePill: "NEW · Free to test",
    scanWithCamera: "Scan with your camera app",
    photosWillAppear: "Photos will appear in this listing automatically",
    waitingForPhotos: "Waiting for photos from phone...",
    doneBtn: "Done",
    doneGenerate: "Done + Generate",
    phoneDisclaimer:
      "This feature will soon be available exclusively to Pro & Business plans.",
    uploadAtLeastOne: "Please upload at least one image.",
    sessionExpired:
      "Your session has expired. Please sign in again via the extension.",
    sessionExpiredShort: "Session expired. Please sign in again.",
    usageLimitExceeded: "You have exceeded your daily/monthly usage limit.",
    upgradePlan: "Upgrade Plan",
    imageUploaded: "Image uploaded!",
    fileAdded: "file added. Ready for more...",
    filesAdded: "files added. Ready for more...",
    signInFirst: "Please sign in via the extension popup first.",
    unexpectedError: "An unexpected error occurred.",
    unlimited: "Unlimited",
  },
  fr: {
    subtitle: "Annonces Vinted intelligentes avec l'IA",
    welcomeBack: "Bon retour",
    signInTo: "Connectez-vous à AutoLister AI",
    continueWithGoogle: "Continuer avec Google",
    or: "OU",
    emailAddress: "Adresse e-mail",
    sendMagicLink: "Envoyer le lien magique",
    needHelp: "Besoin d'aide ?",
    contactSupport: "Contacter le support",
    freePlan: "Gratuit",
    starterPlan: "Plan Starter",
    proPlan: "Plan Pro",
    businessPlan: "Plan Business",
    dailyUsage: "Utilisation quotidienne",
    monthlyUsage: "Utilisation mensuelle",
    totalUsage: "Utilisation totale",
    starter: "Starter",
    pro: "Pro",
    perMonth: "/mois",
    listingsPerDay: "annonces/jour",
    toneEmojiFeature: "Personnalisation ton & émojis",
    popular: "Populaire",
    getStarter: "Choisir Starter",
    getPro: "Choisir Pro",
    compareAllPlans: "Comparer tous les plans",
    activeUntil: "Actif jusqu'au",
    activeSubscription: "Abonnement actif",
    manageSubscription: "Gérer l'abonnement",
    contentLanguage: "Langue du contenu généré",
    selectLanguage: "Choisir la langue",
    signOut: "Déconnexion",
    helperText:
      "Le bouton « Generate » apparaît sur les pages de création d'annonces Vinted.",
    settings: "Paramètres",
    displayLanguage: "Langue d'affichage",
    textFormat: "Format du texte",
    descriptionTone: "Ton de la description",
    toneStandard: "Standard",
    toneFriendly: "Amical",
    tonePro: "Pro",
    toneEnthusiastic: "Enthousiaste",
    useEmojis: "Utiliser les émojis",
    emojiSublabel: "Ajouter des émojis pertinents au texte",
    upgradeToUnlock: "Passez à un plan supérieur :",
    upgradeNote:
      "Les options de ton et les émojis sont disponibles avec les plans Pro et Business.",
    viewPlans: "Voir les plans →",
    loading: "Chargement...",
    processing: "Traitement…",
    newBadge: "NOUVEAU",
    pleaseEnterValidEmail: "Veuillez entrer une adresse e-mail valide.",
    checkEmailForLink: "Consultez vos e-mails pour le lien de connexion.",
    pleaseSignInToUpgrade:
      "Veuillez vous connecter pour passer à un plan supérieur.",
    unableToOpenPayment: "Impossible d'ouvrir la page de paiement.",
    connectionIssue: "Problème de connexion. Veuillez réessayer.",
    pleaseSignInToManage:
      "Veuillez vous connecter pour gérer votre abonnement.",
    unableToOpenSubscription: "Impossible d'ouvrir la page d'abonnement.",
    googleSignInFailed: "La connexion Google a échoué. Veuillez réessayer.",
    popupBlocked:
      "La fenêtre de connexion Google a été bloquée par votre navigateur. Veuillez autoriser les pop-ups et réessayer.",
    generate: "Générer",
    phone: "Téléphone",
    signInToEnable: "Connectez-vous pour les outils IA",
    clickHere: "(Cliquez ici)",
    generating: "⏳ Génération…",
    done: "✅ Terminé",
    uploadFromPhone: "📱 Télécharger depuis le téléphone",
    featurePill: "NOUVEAU · Gratuit à tester",
    scanWithCamera: "Scannez avec l'appareil photo",
    photosWillAppear:
      "Les photos apparaîtront automatiquement dans cette annonce",
    waitingForPhotos: "En attente des photos du téléphone...",
    doneBtn: "Terminé",
    doneGenerate: "Terminé + Générer",
    phoneDisclaimer:
      "Cette fonctionnalité sera bientôt réservée aux plans Pro et Business.",
    uploadAtLeastOne: "Veuillez télécharger au moins une image.",
    sessionExpired:
      "Votre session a expiré. Veuillez vous reconnecter via l'extension.",
    sessionExpiredShort: "Session expirée. Veuillez vous reconnecter.",
    usageLimitExceeded:
      "Vous avez dépassé votre limite d'utilisation quotidienne/mensuelle.",
    upgradePlan: "Changer de plan",
    imageUploaded: "Image téléchargée !",
    fileAdded: "fichier ajouté. Prêt pour d'autres...",
    filesAdded: "fichiers ajoutés. Prêt pour d'autres...",
    signInFirst: "Veuillez d'abord vous connecter via l'extension.",
    unexpectedError: "Une erreur inattendue s'est produite.",
    unlimited: "Illimité",
  },
  de: {
    subtitle: "Smarte Vinted-Anzeigen mit KI",
    welcomeBack: "Willkommen zurück",
    signInTo: "Bei AutoLister AI anmelden",
    continueWithGoogle: "Mit Google fortfahren",
    or: "ODER",
    emailAddress: "E-Mail-Adresse",
    sendMagicLink: "Magic Link senden",
    needHelp: "Hilfe nötig?",
    contactSupport: "Support kontaktieren",
    freePlan: "Kostenlos",
    starterPlan: "Starter-Plan",
    proPlan: "Pro-Plan",
    businessPlan: "Business-Plan",
    dailyUsage: "Tägliche Nutzung",
    monthlyUsage: "Monatliche Nutzung",
    totalUsage: "Gesamtnutzung",
    starter: "Starter",
    pro: "Pro",
    perMonth: "/Monat",
    listingsPerDay: "Anzeigen/Tag",
    toneEmojiFeature: "Ton- & Emoji-Anpassung",
    popular: "Beliebt",
    getStarter: "Starter wählen",
    getPro: "Pro wählen",
    compareAllPlans: "Alle Pläne vergleichen",
    activeUntil: "Aktiv bis",
    activeSubscription: "Aktives Abonnement",
    manageSubscription: "Abonnement verwalten",
    contentLanguage: "Sprache des generierten Inhalts",
    selectLanguage: "Sprache wählen",
    signOut: "Abmelden",
    helperText: 'Der "Generate"-Button erscheint auf Vinted-Anzeigenseiten.',
    settings: "Einstellungen",
    displayLanguage: "Anzeigesprache",
    textFormat: "Textformat",
    descriptionTone: "Beschreibungston",
    toneStandard: "Standard",
    toneFriendly: "Freundlich",
    tonePro: "Pro",
    toneEnthusiastic: "Begeistert",
    useEmojis: "Emojis verwenden",
    emojiSublabel: "Passende Emojis zum Text hinzufügen",
    upgradeToUnlock: "Upgrade zum Freischalten:",
    upgradeNote:
      "Ton-Optionen und Emoji-Verbesserung sind in Pro- und Business-Plänen verfügbar.",
    viewPlans: "Pläne ansehen →",
    loading: "Laden...",
    processing: "Verarbeitung…",
    newBadge: "NEU",
    pleaseEnterValidEmail: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    checkEmailForLink: "Überprüfen Sie Ihre E-Mails für den Anmeldelink.",
    pleaseSignInToUpgrade: "Bitte melden Sie sich an, um upzugraden.",
    unableToOpenPayment: "Die Zahlungsseite konnte nicht geöffnet werden.",
    connectionIssue: "Verbindungsproblem. Bitte versuchen Sie es erneut.",
    pleaseSignInToManage:
      "Bitte melden Sie sich an, um Ihr Abonnement zu verwalten.",
    unableToOpenSubscription:
      "Die Abonnementseite konnte nicht geöffnet werden.",
    googleSignInFailed:
      "Google-Anmeldung fehlgeschlagen. Bitte versuchen Sie es erneut.",
    popupBlocked:
      "Das Google-Anmeldefenster wurde möglicherweise von Ihrem Browser blockiert. Bitte erlauben Sie Pop-ups und versuchen Sie es erneut.",
    generate: "Generieren",
    phone: "Handy",
    signInToEnable: "Anmelden für KI-Tools",
    clickHere: "(Hier klicken)",
    generating: "⏳ Generierung…",
    done: "✅ Fertig",
    uploadFromPhone: "📱 Vom Handy hochladen",
    featurePill: "NEU · Kostenlos testen",
    scanWithCamera: "Mit der Kamera-App scannen",
    photosWillAppear: "Fotos erscheinen automatisch in dieser Anzeige",
    waitingForPhotos: "Warte auf Fotos vom Handy...",
    doneBtn: "Fertig",
    doneGenerate: "Fertig + Generieren",
    phoneDisclaimer:
      "Diese Funktion wird bald nur für Pro- und Business-Pläne verfügbar sein.",
    uploadAtLeastOne: "Bitte laden Sie mindestens ein Bild hoch.",
    sessionExpired:
      "Ihre Sitzung ist abgelaufen. Bitte melden Sie sich erneut über die Erweiterung an.",
    sessionExpiredShort: "Sitzung abgelaufen. Bitte erneut anmelden.",
    usageLimitExceeded:
      "Sie haben Ihr tägliches/monatliches Nutzungslimit überschritten.",
    upgradePlan: "Plan upgraden",
    imageUploaded: "Bild hochgeladen!",
    fileAdded: "Datei hinzugefügt. Bereit für mehr...",
    filesAdded: "Dateien hinzugefügt. Bereit für mehr...",
    signInFirst: "Bitte melden Sie sich zuerst über die Erweiterung an.",
    unexpectedError: "Ein unerwarteter Fehler ist aufgetreten.",
    unlimited: "Unbegrenzt",
  },
  es: {
    subtitle: "Anuncios Vinted inteligentes con IA",
    welcomeBack: "Bienvenido de nuevo",
    signInTo: "Inicia sesión en AutoLister AI",
    continueWithGoogle: "Continuar con Google",
    or: "O",
    emailAddress: "Correo electrónico",
    sendMagicLink: "Enviar enlace mágico",
    needHelp: "¿Necesitas ayuda?",
    contactSupport: "Contactar soporte",
    freePlan: "Gratuito",
    starterPlan: "Plan Starter",
    proPlan: "Plan Pro",
    businessPlan: "Plan Business",
    dailyUsage: "Uso diario",
    monthlyUsage: "Uso mensual",
    totalUsage: "Uso total",
    starter: "Starter",
    pro: "Pro",
    perMonth: "/mes",
    listingsPerDay: "anuncios/día",
    toneEmojiFeature: "Personalización de tono y emojis",
    popular: "Popular",
    getStarter: "Elegir Starter",
    getPro: "Elegir Pro",
    compareAllPlans: "Comparar todos los planes",
    activeUntil: "Activo hasta",
    activeSubscription: "Suscripción activa",
    manageSubscription: "Gestionar suscripción",
    contentLanguage: "Idioma del contenido generado",
    selectLanguage: "Seleccionar idioma",
    signOut: "Cerrar sesión",
    helperText:
      'El botón "Generate" aparece en las páginas de creación de anuncios de Vinted.',
    settings: "Ajustes",
    displayLanguage: "Idioma de la interfaz",
    textFormat: "Formato de texto",
    descriptionTone: "Tono de la descripción",
    toneStandard: "Estándar",
    toneFriendly: "Amigable",
    tonePro: "Pro",
    toneEnthusiastic: "Entusiasta",
    useEmojis: "Usar emojis",
    emojiSublabel: "Añadir emojis relevantes al texto",
    upgradeToUnlock: "Mejora para desbloquear:",
    upgradeNote:
      "Las opciones de tono y emojis están disponibles en los planes Pro y Business.",
    viewPlans: "Ver planes →",
    loading: "Cargando...",
    processing: "Procesando…",
    newBadge: "NUEVO",
    pleaseEnterValidEmail: "Por favor, introduce un correo electrónico válido.",
    checkEmailForLink: "Revisa tu correo para el enlace de inicio de sesión.",
    pleaseSignInToUpgrade: "Por favor, inicia sesión para mejorar tu plan.",
    unableToOpenPayment: "No se pudo abrir la página de pago.",
    connectionIssue: "Problema de conexión. Inténtalo de nuevo.",
    pleaseSignInToManage:
      "Por favor, inicia sesión para gestionar tu suscripción.",
    unableToOpenSubscription: "No se pudo abrir la página de suscripción.",
    googleSignInFailed: "Error en la conexión con Google. Inténtalo de nuevo.",
    popupBlocked:
      "La ventana de Google fue bloqueada por tu navegador. Permite las ventanas emergentes e inténtalo de nuevo.",
    generate: "Generar",
    phone: "Teléfono",
    signInToEnable: "Inicia sesión para herramientas IA",
    clickHere: "(Haz clic aquí)",
    generating: "⏳ Generando…",
    done: "✅ Hecho",
    uploadFromPhone: "📱 Subir desde el teléfono",
    featurePill: "NUEVO · Gratis para probar",
    scanWithCamera: "Escanea con la app de cámara",
    photosWillAppear: "Las fotos aparecerán automáticamente en este anuncio",
    waitingForPhotos: "Esperando fotos del teléfono...",
    doneBtn: "Hecho",
    doneGenerate: "Hecho + Generar",
    phoneDisclaimer:
      "Esta función pronto será exclusiva de los planes Pro y Business.",
    uploadAtLeastOne: "Por favor, sube al menos una imagen.",
    sessionExpired:
      "Tu sesión ha expirado. Inicia sesión de nuevo desde la extensión.",
    sessionExpiredShort: "Sesión expirada. Inicia sesión de nuevo.",
    usageLimitExceeded: "Has superado tu límite de uso diario/mensual.",
    upgradePlan: "Mejorar plan",
    imageUploaded: "¡Imagen subida!",
    fileAdded: "archivo añadido. Listo para más...",
    filesAdded: "archivos añadidos. Listo para más...",
    signInFirst: "Primero inicia sesión desde la extensión.",
    unexpectedError: "Se produjo un error inesperado.",
    unlimited: "Ilimitado",
  },
  it: {
    subtitle: "Annunci Vinted intelligenti con l'IA",
    welcomeBack: "Bentornato",
    signInTo: "Accedi a AutoLister AI",
    continueWithGoogle: "Continua con Google",
    or: "O",
    emailAddress: "Indirizzo e-mail",
    sendMagicLink: "Invia link magico",
    needHelp: "Hai bisogno di aiuto?",
    contactSupport: "Contatta il supporto",
    freePlan: "Gratuito",
    starterPlan: "Piano Starter",
    proPlan: "Piano Pro",
    businessPlan: "Piano Business",
    dailyUsage: "Utilizzo giornaliero",
    monthlyUsage: "Utilizzo mensile",
    totalUsage: "Utilizzo totale",
    starter: "Starter",
    pro: "Pro",
    perMonth: "/mese",
    listingsPerDay: "annunci/giorno",
    toneEmojiFeature: "Personalizzazione tono ed emoji",
    popular: "Popolare",
    getStarter: "Scegli Starter",
    getPro: "Scegli Pro",
    compareAllPlans: "Confronta tutti i piani",
    activeUntil: "Attivo fino al",
    activeSubscription: "Abbonamento attivo",
    manageSubscription: "Gestisci abbonamento",
    contentLanguage: "Lingua del contenuto generato",
    selectLanguage: "Seleziona lingua",
    signOut: "Esci",
    helperText:
      'Il pulsante "Generate" appare sulle pagine di creazione annunci di Vinted.',
    settings: "Impostazioni",
    displayLanguage: "Lingua dell'interfaccia",
    textFormat: "Formato testo",
    descriptionTone: "Tono della descrizione",
    toneStandard: "Standard",
    toneFriendly: "Amichevole",
    tonePro: "Pro",
    toneEnthusiastic: "Entusiasta",
    useEmojis: "Usa emoji",
    emojiSublabel: "Aggiungi emoji pertinenti al testo",
    upgradeToUnlock: "Aggiorna per sbloccare:",
    upgradeNote:
      "Le opzioni di tono e gli emoji sono disponibili nei piani Pro e Business.",
    viewPlans: "Vedi piani →",
    loading: "Caricamento...",
    processing: "Elaborazione…",
    newBadge: "NUOVO",
    pleaseEnterValidEmail: "Inserisci un indirizzo e-mail valido.",
    checkEmailForLink: "Controlla la tua e-mail per il link di accesso.",
    pleaseSignInToUpgrade: "Accedi per aggiornare il tuo piano.",
    unableToOpenPayment: "Impossibile aprire la pagina di pagamento.",
    connectionIssue: "Problema di connessione. Riprova.",
    pleaseSignInToManage: "Accedi per gestire il tuo abbonamento.",
    unableToOpenSubscription: "Impossibile aprire la pagina dell'abbonamento.",
    googleSignInFailed: "Accesso Google non riuscito. Riprova tra un momento.",
    popupBlocked:
      "La finestra di accesso Google è stata bloccata dal browser. Consenti i popup e riprova.",
    generate: "Genera",
    phone: "Telefono",
    signInToEnable: "Accedi per gli strumenti IA",
    clickHere: "(Clicca qui)",
    generating: "⏳ Generazione…",
    done: "✅ Fatto",
    uploadFromPhone: "📱 Carica dal telefono",
    featurePill: "NUOVO · Gratis da provare",
    scanWithCamera: "Scansiona con l'app fotocamera",
    photosWillAppear: "Le foto appariranno automaticamente in questo annuncio",
    waitingForPhotos: "In attesa delle foto dal telefono...",
    doneBtn: "Fatto",
    doneGenerate: "Fatto + Genera",
    phoneDisclaimer:
      "Questa funzione sarà presto esclusiva dei piani Pro e Business.",
    uploadAtLeastOne: "Carica almeno un'immagine.",
    sessionExpired: "La sessione è scaduta. Accedi di nuovo dall'estensione.",
    sessionExpiredShort: "Sessione scaduta. Accedi di nuovo.",
    usageLimitExceeded:
      "Hai superato il limite di utilizzo giornaliero/mensile.",
    upgradePlan: "Aggiorna piano",
    imageUploaded: "Immagine caricata!",
    fileAdded: "file aggiunto. Pronto per altri...",
    filesAdded: "file aggiunti. Pronto per altri...",
    signInFirst: "Prima accedi dall'estensione.",
    unexpectedError: "Si è verificato un errore imprevisto.",
    unlimited: "Illimitato",
  },
  nl: {
    subtitle: "Slimme Vinted-advertenties met AI",
    welcomeBack: "Welkom terug",
    signInTo: "Inloggen bij AutoLister AI",
    continueWithGoogle: "Doorgaan met Google",
    or: "OF",
    emailAddress: "E-mailadres",
    sendMagicLink: "Magic link versturen",
    needHelp: "Hulp nodig?",
    contactSupport: "Contact opnemen",
    freePlan: "Gratis",
    starterPlan: "Starter-plan",
    proPlan: "Pro-plan",
    businessPlan: "Business-plan",
    dailyUsage: "Dagelijks gebruik",
    monthlyUsage: "Maandelijks gebruik",
    totalUsage: "Totaal gebruik",
    starter: "Starter",
    pro: "Pro",
    perMonth: "/maand",
    listingsPerDay: "advertenties/dag",
    toneEmojiFeature: "Toon- & emoji-aanpassing",
    popular: "Populair",
    getStarter: "Kies Starter",
    getPro: "Kies Pro",
    compareAllPlans: "Alle plannen vergelijken",
    activeUntil: "Actief tot",
    activeSubscription: "Actief abonnement",
    manageSubscription: "Abonnement beheren",
    contentLanguage: "Taal van gegenereerde inhoud",
    selectLanguage: "Taal kiezen",
    signOut: "Uitloggen",
    helperText: 'De "Generate"-knop verschijnt op Vinted-advertentiepagina\'s.',
    settings: "Instellingen",
    displayLanguage: "Weergavetaal",
    textFormat: "Tekstformaat",
    descriptionTone: "Beschrijvingstoon",
    toneStandard: "Standaard",
    toneFriendly: "Vriendelijk",
    tonePro: "Pro",
    toneEnthusiastic: "Enthousiast",
    useEmojis: "Emoji's gebruiken",
    emojiSublabel: "Relevante emoji's aan tekst toevoegen",
    upgradeToUnlock: "Upgrade om te ontgrendelen:",
    upgradeNote:
      "Toon-opties en emoji's zijn beschikbaar in Pro- en Business-plannen.",
    viewPlans: "Plannen bekijken →",
    loading: "Laden...",
    processing: "Verwerken…",
    newBadge: "NIEUW",
    pleaseEnterValidEmail: "Voer een geldig e-mailadres in.",
    checkEmailForLink: "Controleer je e-mail voor de inloglink.",
    pleaseSignInToUpgrade: "Log in om je plan te upgraden.",
    unableToOpenPayment: "Kan de betaalpagina niet openen.",
    connectionIssue: "Verbindingsprobleem. Probeer het opnieuw.",
    pleaseSignInToManage: "Log in om je abonnement te beheren.",
    unableToOpenSubscription: "Kan de abonnementspagina niet openen.",
    googleSignInFailed: "Google-aanmelding mislukt. Probeer het opnieuw.",
    popupBlocked:
      "Het Google-aanmeldvenster werd geblokkeerd door je browser. Sta pop-ups toe en probeer het opnieuw.",
    generate: "Genereren",
    phone: "Telefoon",
    signInToEnable: "Log in voor AI-tools",
    clickHere: "(Klik hier)",
    generating: "⏳ Genereren…",
    done: "✅ Klaar",
    uploadFromPhone: "📱 Uploaden vanaf telefoon",
    featurePill: "NIEUW · Gratis testen",
    scanWithCamera: "Scan met je camera-app",
    photosWillAppear: "Foto's verschijnen automatisch in deze advertentie",
    waitingForPhotos: "Wachten op foto's van telefoon...",
    doneBtn: "Klaar",
    doneGenerate: "Klaar + Genereren",
    phoneDisclaimer:
      "Deze functie wordt binnenkort exclusief voor Pro- en Business-plannen.",
    uploadAtLeastOne: "Upload minimaal één afbeelding.",
    sessionExpired: "Je sessie is verlopen. Log opnieuw in via de extensie.",
    sessionExpiredShort: "Sessie verlopen. Log opnieuw in.",
    usageLimitExceeded:
      "Je hebt je dagelijkse/maandelijkse gebruikslimiet overschreden.",
    upgradePlan: "Plan upgraden",
    imageUploaded: "Afbeelding geüpload!",
    fileAdded: "bestand toegevoegd. Klaar voor meer...",
    filesAdded: "bestanden toegevoegd. Klaar voor meer...",
    signInFirst: "Log eerst in via de extensie.",
    unexpectedError: "Er is een onverwachte fout opgetreden.",
    unlimited: "Onbeperkt",
  },
  pl: {
    subtitle: "Inteligentne ogłoszenia Vinted z AI",
    welcomeBack: "Witamy ponownie",
    signInTo: "Zaloguj się do AutoLister AI",
    continueWithGoogle: "Kontynuuj z Google",
    or: "LUB",
    emailAddress: "Adres e-mail",
    sendMagicLink: "Wyślij link magiczny",
    needHelp: "Potrzebujesz pomocy?",
    contactSupport: "Skontaktuj się z pomocą",
    freePlan: "Darmowy",
    starterPlan: "Plan Starter",
    proPlan: "Plan Pro",
    businessPlan: "Plan Business",
    dailyUsage: "Użycie dzienne",
    monthlyUsage: "Użycie miesięczne",
    totalUsage: "Łączne użycie",
    starter: "Starter",
    pro: "Pro",
    perMonth: "/mies.",
    listingsPerDay: "ogłoszeń/dzień",
    toneEmojiFeature: "Personalizacja tonu i emoji",
    popular: "Popularny",
    getStarter: "Wybierz Starter",
    getPro: "Wybierz Pro",
    compareAllPlans: "Porównaj wszystkie plany",
    activeUntil: "Aktywny do",
    activeSubscription: "Aktywna subskrypcja",
    manageSubscription: "Zarządzaj subskrypcją",
    contentLanguage: "Język generowanej treści",
    selectLanguage: "Wybierz język",
    signOut: "Wyloguj się",
    helperText:
      'Przycisk "Generate" pojawia się na stronach tworzenia ogłoszeń Vinted.',
    settings: "Ustawienia",
    displayLanguage: "Język interfejsu",
    textFormat: "Format tekstu",
    descriptionTone: "Ton opisu",
    toneStandard: "Standardowy",
    toneFriendly: "Przyjazny",
    tonePro: "Pro",
    toneEnthusiastic: "Entuzjastyczny",
    useEmojis: "Używaj emoji",
    emojiSublabel: "Dodaj odpowiednie emoji do tekstu",
    upgradeToUnlock: "Ulepsz, aby odblokować:",
    upgradeNote: "Opcje tonu i emoji są dostępne w planach Pro i Business.",
    viewPlans: "Zobacz plany →",
    loading: "Ładowanie...",
    processing: "Przetwarzanie…",
    newBadge: "NOWE",
    pleaseEnterValidEmail: "Wprowadź prawidłowy adres e-mail.",
    checkEmailForLink: "Sprawdź e-mail, aby znaleźć link do logowania.",
    pleaseSignInToUpgrade: "Zaloguj się, aby ulepszyć plan.",
    unableToOpenPayment: "Nie można otworzyć strony płatności.",
    connectionIssue: "Problem z połączeniem. Spróbuj ponownie.",
    pleaseSignInToManage: "Zaloguj się, aby zarządzać subskrypcją.",
    unableToOpenSubscription: "Nie można otworzyć strony subskrypcji.",
    googleSignInFailed:
      "Logowanie przez Google nie powiodło się. Spróbuj ponownie.",
    popupBlocked:
      "Okno logowania Google zostało zablokowane przez przeglądarkę. Zezwól na wyskakujące okna i spróbuj ponownie.",
    generate: "Generuj",
    phone: "Telefon",
    signInToEnable: "Zaloguj się, aby włączyć narzędzia AI",
    clickHere: "(Kliknij tutaj)",
    generating: "⏳ Generowanie…",
    done: "✅ Gotowe",
    uploadFromPhone: "📱 Prześlij z telefonu",
    featurePill: "NOWE · Bezpłatne do przetestowania",
    scanWithCamera: "Zeskanuj aparatem",
    photosWillAppear: "Zdjęcia pojawią się automatycznie w tym ogłoszeniu",
    waitingForPhotos: "Oczekiwanie na zdjęcia z telefonu...",
    doneBtn: "Gotowe",
    doneGenerate: "Gotowe + Generuj",
    phoneDisclaimer:
      "Ta funkcja będzie wkrótce dostępna wyłącznie w planach Pro i Business.",
    uploadAtLeastOne: "Prześlij co najmniej jedno zdjęcie.",
    sessionExpired: "Sesja wygasła. Zaloguj się ponownie przez rozszerzenie.",
    sessionExpiredShort: "Sesja wygasła. Zaloguj się ponownie.",
    usageLimitExceeded: "Przekroczono dzienny/miesięczny limit użycia.",
    upgradePlan: "Ulepsz plan",
    imageUploaded: "Zdjęcie przesłane!",
    fileAdded: "plik dodany. Gotowe na więcej...",
    filesAdded: "pliki dodane. Gotowe na więcej...",
    signInFirst: "Najpierw zaloguj się przez rozszerzenie.",
    unexpectedError: "Wystąpił nieoczekiwany błąd.",
    unlimited: "Bez limitu",
  },
};

// Supported UI language codes (for the display language picker)
const UI_LANGUAGES = [
  { code: "en", name: "English", flag: "gb" },
  { code: "fr", name: "Français", flag: "fr" },
  { code: "de", name: "Deutsch", flag: "de" },
  { code: "es", name: "Español", flag: "es" },
  { code: "it", name: "Italiano", flag: "it" },
  { code: "nl", name: "Nederlands", flag: "nl" },
  { code: "pl", name: "Polski", flag: "pl" },
];

/**
 * Detects the best UI language code based on timezone + browser language.
 * Returns one of the supported codes: en, fr, de, es, it, nl, pl
 */
function detectUILanguageCode() {
  // Try timezone first
  if (typeof Intl !== "undefined") {
    try {
      const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
      const tzMap = {
        "Europe/Paris": "fr",
        "Europe/Berlin": "de",
        "Europe/Madrid": "es",
        "Europe/Rome": "it",
        "Europe/Amsterdam": "nl",
        "Europe/Brussels": "fr",
        "Europe/Warsaw": "pl",
      };
      if (tzMap[tz]) return tzMap[tz];
    } catch (e) {
      /* ignore */
    }
  }
  // Fallback to navigator.language
  if (typeof navigator !== "undefined" && navigator.language) {
    const lang = navigator.language.toLowerCase().split("-")[0];
    if (UI_STRINGS[lang]) return lang;
  }
  return "en";
}

/**
 * Returns the UI strings for the given language code, falling back to English.
 */
function getUIStrings(langCode) {
  return UI_STRINGS[langCode] || UI_STRINGS.en;
}

// Export to global scope
if (typeof window !== "undefined") {
  window.UI_STRINGS = UI_STRINGS;
  window.UI_LANGUAGES = UI_LANGUAGES;
  window.detectUILanguageCode = detectUILanguageCode;
  window.getUIStrings = getUIStrings;
}

const LOCALIZATION = {
  FR: {
    domain: "vinted.fr",
    currency: "€",
    texts: {
      welcomeTitle: "Bienvenue sur AutoLister AI !",
      welcomeSubtitle:
        "Vous êtes connecté et prêt à créer des annonces incroyables avec l'IA.",
      welcomeMessage:
        "Retournez sur Vinted, le bouton 🪄 Generate apparaîtra lors de la création d'annonces !",
      featuresTitle: "✨ Ce que vous pouvez faire maintenant",
      feature1:
        "Générer des titres et descriptions convaincants instantanément",
      feature2:
        "Télécharger des photos et obtenir des annonces alimentées par l'IA",
      feature3: "Économiser des heures de rédaction manuelle",
      feature4: "Essayez gratuitement avec 5 annonces par mois",
      upgradeTitle: "💡 Vous voulez plus de puissance ?",
      upgradeDescription:
        "Testez avec 5 annonces gratuites par mois. Passez à la version supérieure pour obtenir jusqu'à 50 annonces par jour, un support prioritaire et plus de fonctionnalités !",
      starterFeatures: "5 annonces/jour<br>Parfait pour vendeurs occasionnels",
      proFeatures: "15 annonces/jour<br>Pour vendeurs actifs",
      businessFeatures: "50 annonces/jour<br>Pour vendeurs professionnels",
      privacyLink: "Politique de confidentialité",
      termsLink: "Conditions d'utilisation",
      // New keys
      closeTabButton: "Fermer l'onglet",
      vintedButton: "Créer sur Vinted.fr",
      viewPlansButton: "Voir tous les plans",
      onboardingTitle: "Prêt à vendre ?",
      onboardingImageAlt: "Aperçu de l'outil AutoLister sur Vinted",
    },
  },
  DE: {
    domain: "vinted.de",
    currency: "€",
    texts: {
      welcomeTitle: "Willkommen bei AutoLister AI!",
      welcomeSubtitle:
        "Sie sind angemeldet und bereit, fantastische Anzeigen mit KI zu erstellen.",
      welcomeMessage:
        "Gehen Sie zurück zu Vinted, der 🪄 Generate Button erscheint, wenn Sie neue Anzeigen erstellen!",
      featuresTitle: "✨ Was Sie jetzt tun können",
      feature1: "Überzeugende Titel und Beschreibungen sofort generieren",
      feature2: "Fotos hochladen und KI-gestützte Anzeigen erhalten",
      feature3: "Stunden manueller Schreibarbeit sparen",
      feature4: "Kostenlos testen mit 5 Anzeigen pro Monat",
      upgradeTitle: "💡 Möchten Sie mehr Power?",
      upgradeDescription:
        "Testen Sie mit 5 kostenlosen Anzeigen pro Monat. Upgraden Sie, um bis zu 50 Anzeigen pro Tag, Priority-Support und mehr Features zu erhalten!",
      starterFeatures: "5 Anzeigen/Tag<br>Perfekt für Gelegenheitsverkäufer",
      proFeatures: "15 Anzeigen/Tag<br>Für aktive Verkäufer",
      businessFeatures: "50 Anzeigen/Tag<br>Für professionelle Verkäufer",
      privacyLink: "Datenschutzerklärung",
      termsLink: "Nutzungsbedingungen",
      // New keys
      closeTabButton: "Tab schließen",
      vintedButton: "Auf Vinted.de erstellen",
      viewPlansButton: "Alle Pläne anzeigen",
      onboardingTitle: "Bereit zu verkaufen?",
      onboardingImageAlt: "Vorschau des AutoLister-Tools auf Vinted",
    },
  },
  PL: {
    domain: "vinted.pl",
    currency: "zł",
    texts: {
      welcomeTitle: "Witamy w AutoLister AI!",
      welcomeSubtitle:
        "Jesteś zalogowany i gotowy do tworzenia niesamowitych ogłoszeń z pomocą AI.",
      welcomeMessage:
        "Wróć do Vinted, przycisk 🪄 Generate pojawi się, gdy będziesz tworzyć nowe ogłoszenia!",
      featuresTitle: "✨ Co możesz teraz zrobić",
      feature1: "Natychmiast generuj przekonujące tytuły i opisy",
      feature2: "Przesyłaj zdjęcia i otrzymuj ogłoszenia wspierane przez AI",
      feature3: "Oszczędzaj godziny ręcznego pisania",
      feature4: "Wypróbuj za darmo z 5 ogłoszeniami miesięcznie",
      upgradeTitle: "💡 Chcesz więcej mocy?",
      upgradeDescription:
        "Wypróbuj z 5 darmowymi ogłoszeniami miesięcznie. Ulepsz, aby uzyskać nawet 50 ogłoszeń dziennie, priorytetowe wsparcie i więcej funkcji!",
      starterFeatures:
        "5 ogłoszeń/dzień<br>Idealne dla okazjonalnych sprzedawców",
      proFeatures: "15 ogłoszeń/dzień<br>Dla aktywnych sprzedawców",
      businessFeatures: "50 ogłoszeń/dzień<br>Dla profesjonalnych sprzedawców",
      privacyLink: "Polityka prywatności",
      termsLink: "Warunki świadczenia usług",
      // New keys
      closeTabButton: "Zamknij kartę",
      vintedButton: "Twórz na Vinted.pl",
      viewPlansButton: "Zobacz wszystkie plany",
      onboardingTitle: "Gotowy do sprzedaży?",
      onboardingImageAlt: "Podgląd narzędzia AutoLister na Vinted",
    },
  },
  ES: {
    domain: "vinted.es",
    currency: "€",
    texts: {
      welcomeTitle: "¡Bienvenido a AutoLister AI!",
      welcomeSubtitle:
        "Has iniciado sesión y estás listo para crear increíbles anuncios con IA.",
      welcomeMessage:
        "Vuelve a Vinted, el botón 🪄 Generate aparecerá cuando crees nuevos anuncios.",
      featuresTitle: "✨ Lo que puedes hacer ahora",
      feature1: "Generar títulos y descripciones convincentes al instante",
      feature2: "Subir fotos y obtener anuncios potenciados por IA",
      feature3: "Ahorrar horas de escritura manual",
      feature4: "Prueba gratis con 5 anuncios al mes",
      upgradeTitle: "💡 ¿Quieres más potencia?",
      upgradeDescription:
        "Prueba con 5 anuncios gratuitos al mes. ¡Actualiza para obtener hasta 50 anuncios diarios, soporte prioritario y más características!",
      starterFeatures: "5 anuncios/día<br>Perfecto para vendedores ocasionales",
      proFeatures: "15 anuncios/día<br>Para vendedores activos",
      businessFeatures: "50 anuncios/día<br>Para vendedores profesionales",
      privacyLink: "Política de privacidad",
      termsLink: "Términos de servicio",
      // New keys
      closeTabButton: "Cerrar pestaña",
      vintedButton: "Crear en Vinted.es",
      viewPlansButton: "Ver todos los planes",
      onboardingTitle: "¿Listo para vender?",
      onboardingImageAlt: "Vista previa de la herramienta AutoLister en Vinted",
    },
  },
  IT: {
    domain: "vinted.it",
    currency: "€",
    texts: {
      welcomeTitle: "Benvenuto su AutoLister AI!",
      welcomeSubtitle:
        "Hai effettuato l'accesso e sei pronto per creare annunci fantastici con l'IA.",
      welcomeMessage:
        "Torna su Vinted, il pulsante 🪄 Generate apparirà quando crei nuovi annunci!",
      featuresTitle: "✨ Cosa puoi fare ora",
      feature1: "Generare titoli e descrizioni convincenti istantaneamente",
      feature2: "Caricare foto e ottenere annunci potenziati dall'IA",
      feature3: "Risparmiare ore di scrittura manuale",
      feature4: "Prova gratis con 5 annunci al mese",
      upgradeTitle: "💡 Vuoi più potenza?",
      upgradeDescription:
        "Prova con 5 annunci gratuiti al mese. Aggiorna per ottenere fino a 50 annunci al giorno, supporto prioritario e più funzionalità!",
      starterFeatures: "5 annunci/giorno<br>Perfetto per venditori occasionali",
      proFeatures: "15 annunci/giorno<br>Per venditori attivi",
      businessFeatures: "50 annunci/giorno<br>Per venditori professionali",
      privacyLink: "Informativa sulla privacy",
      termsLink: "Termini di servizio",
      // New keys
      closeTabButton: "Chiudi scheda",
      vintedButton: "Crea su Vinted.it",
      viewPlansButton: "Visualizza tutti i piani",
      onboardingTitle: "Pronto a vendere?",
      onboardingImageAlt: "Anteprima dello strumento AutoLister su Vinted",
    },
  },
  NL: {
    domain: "vinted.nl",
    currency: "€",
    texts: {
      welcomeTitle: "Welkom bij AutoLister AI!",
      welcomeSubtitle:
        "Je bent ingelogd en klaar om geweldige advertenties te maken met AI.",
      welcomeMessage:
        "Ga terug naar Vinted, de 🪄 Generate knop verschijnt bij het maken van nieuwe advertenties!",
      featuresTitle: "✨ Wat je nu kunt doen",
      feature1: "Overtuigende titels en beschrijvingen direct genereren",
      feature2: "Foto's uploaden en AI-aangedreven advertenties krijgen",
      feature3: "Uren handmatig schrijven besparen",
      feature4: "Probeer gratis met 5 advertenties per maand",
      upgradeTitle: "💡 Wil je meer kracht?",
      upgradeDescription:
        "Probeer met 5 gratis advertenties per maand. Upgrade om tot 50 dagelijkse advertenties, prioriteitsondersteuning en meer functies te krijgen!",
      starterFeatures:
        "5 advertenties/dag<br>Perfect voor occasionele verkopers",
      proFeatures: "15 advertenties/dag<br>Voor actieve verkopers",
      businessFeatures: "50 advertenties/dag<br>Voor professionele verkopers",
      privacyLink: "Privacybeleid",
      termsLink: "Servicevoorwaarden",
      // New keys
      closeTabButton: "Tabblad sluiten",
      vintedButton: "Maak op Vinted.nl",
      viewPlansButton: "Bekijk alle plannen",
      onboardingTitle: "Klaar om te verkopen?",
      onboardingImageAlt: "Voorbeeld van de AutoLister-tool op Vinted",
    },
  },
  DEFAULT: {
    domain: "vinted.com",
    currency: "€",
    texts: {
      welcomeTitle: "Welcome to AutoLister AI!",
      welcomeSubtitle:
        "You're signed in and ready to create amazing listings with AI.",
      welcomeMessage:
        "Head back to Vinted, the 🪄 Generate button will appear when you create new listings!",
      featuresTitle: "✨ What You Can Do Now",
      feature1: "Generate compelling titles and descriptions instantly",
      feature2: "Upload photos and get AI-powered listings",
      feature3: "Save hours of manual writing",
      feature4: "Try free with 5 listings per month",
      upgradeTitle: "💡 Want More Power?",
      upgradeDescription:
        "Try with 5 free listings per month. Upgrade to get up to 50 daily listings, priority support, and more features!",
      starterFeatures: "5 listings/day<br>Perfect for casual sellers",
      proFeatures: "15 listings/day<br>For active sellers",
      businessFeatures: "50 listings/day<br>For power sellers",
      privacyLink: "Privacy Policy",
      termsLink: "Terms of Service",
      // New keys
      closeTabButton: "Close Tab",
      vintedButton: "Start Creating on Vinted.com",
      viewPlansButton: "View All Plans",
      onboardingTitle: "Ready to list?",
      onboardingImageAlt: "Preview of AutoLister tool on Vinted",
    },
  },
};

function detectCountryAndLocalization() {
  let countryCode = "DEFAULT";

  // Primary detection via timezone (most reliable)
  if (typeof Intl !== "undefined") {
    try {
      const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
      const timezoneMap = {
        "Europe/Paris": "FR",
        "Europe/Berlin": "DE",
        "Europe/Madrid": "ES",
        "Europe/Rome": "IT",
        "Europe/Amsterdam": "NL",
        "Europe/Brussels": "NL", // Belgium often uses Dutch for Vinted
        "Europe/Warsaw": "PL",
      };

      if (timezoneMap[timezone]) {
        countryCode = timezoneMap[timezone];
      }
    } catch (e) {
      console.warn("Timezone detection failed:", e);
    }
  }

  // Fallback to language detection
  if (countryCode === "DEFAULT" && navigator.language) {
    const lang = navigator.language.toLowerCase();
    if (lang.startsWith("fr")) countryCode = "FR";
    else if (lang.startsWith("de")) countryCode = "DE";
    else if (lang.startsWith("es")) countryCode = "ES";
    else if (lang.startsWith("it")) countryCode = "IT";
    else if (lang.startsWith("nl")) countryCode = "NL";
    else if (lang.startsWith("pl")) countryCode = "PL";
  }

  return LOCALIZATION[countryCode] || LOCALIZATION.DEFAULT;
}

// Export to global scope for callback.js
window.LOCALIZATION = LOCALIZATION;
window.detectCountryAndLocalization = detectCountryAndLocalization;
